
print ("Calculadora IMC")
print ("Vamos a calcular el Indice de Masa Corporal según tu peso y estatura")
print ("Para esto primero te pediremos algunos datos")
nombre = str(input("¿Cuál es tu nombre o nombres?: "))
apellido1 = str(input("¿Cuál es tu apellido paterno?: "))
apellido2 = str(input("¿Cuál es tu apellido materno?: "))
estatura = float(input("¿Cuál es tu estatura en metros?: "))
peso = int(input("Cual es tu peso en kilos?: "))
print ("Hola", nombre + apellido1 + apellido2)
print ("por tu estatura de", estatura, ("mtos"))
print ("y tu peso ", peso, ("Kg"))
print (f"Tu IMC es: {peso/estatura**2 : .2f}")
print ("Muchas gracias por tu participación")
input ("Presione cualquier letra para cerrar el programa, gracias")