print ("Calculadora IMC")
print ("Vamos a calcular el Indice de Masa Corporal segun tu peso y estatura")
print ("Para esto primero te pediremos algunos datos")
nombre = str(input("¿Cuál es tu nombre o nombres?: "))
apellido1 = str(input("¿Cuál es tu apellido paterno?: "))
apellido2 = str(input("¿Cuál es tu apellido materno?: "))
edad = int(input("¿Cuál es tu edad?: "))
peso = int(input("Cual es tu peso en kilos?: "))
print ("Hola", nombre, apellido1, apellido2)
print ("por tu edad de", edad, ("años"))
print ("y tu peso ", peso, ("Kg"))
print ("Tú IMC es: ", peso/edad**2)
print ("Muchas gracias por tu participación")
input ("Presione cualquier letra para cerrar el programa, gracias")